#!/bin/bash

S=$@
count=0

while read line
do
	user=$(echo $line | cut -d ':' -f 1)
	for var in ${S[@]}
	do
		if [ $user == $var ]
		then
			count=$((count+1))
		fi
	done	
done < /etc/passwd

exit $count
